# @package _global_
"PROBE_MODEL_NAME": "probe-cifar10b-5k-1k-60e-adam-e35a"
"ENV_DATASET": "cifar10b"

"ENT_COEF_LISTENER": 0.07
"ENT_COEF_SPEAKER": 0.001
"L2_REG_COEF_LISTENER": 1e-2
"L2_REG_COEF_SPEAKER": 1e-3
"LISTENER_LR_SCHEDULE": 1e-5 #"1e-4 jump to 1e-6 at 300"
"SPEAKER_LR_SCHEDULE": 1e-4


"NUM_STEPS": 1024 # 1024
"UPDATE_EPOCHS": 2000
"MINIBATCH_SIZE_LISTENER": 64 # 64 # This must be a whole divisor of NUM_STEPS
"MINIBATCH_SIZE_SPEAKER": 64 # 64 # This must be a whole divisor of NUM_STEPS
"ENV_NUM_DATAPOINTS": 5000

"ENV_KWARGS":
  # ${ENV_KWARGS}:  # This doesn't look right
  "image_dim": 32 # 28 for MNIST, 32 for CIFAR
  "speaker_action_transform": "splines_weight"
  "speaker_action_dim": 21  # This must be a multiple of 6 for "splines", 7 for "splines_weight"
  "num_classes": 12
  "speaker_referent_span_fn": 12


"ENV_DATASET_CATEGORIES": {
    # "apple": 0,
    # "aquarium_fish": 1,
    # "baby": 2,
    # "bear": 3,
    # "beaver": 4,
    # "bed": 5,
    # "bee": 6,
    # "beetle": 7,
    "bicycle": 8,
    # "bottle": 9,
    # "bowl": 10,
    # "boy": 11,
    # "bridge": 12,
    # "bus": 13,
    "butterfly": 14,
    "camel": 15,
    # "can": 16,
    # "castle": 17,
    # "caterpillar": 18,
    # "cattle": 19,
    # "chair": 20,
    # "chimpanzee": 21,
    # "clock": 22,
    # "cloud": 23,
    # "cockroach": 24,
    # "couch": 25,
    "crab": 26,
    # "crocodile": 27,
    # "cup": 28,
    # "dinosaur": 29,
    "dolphin": 30,
    # "elephant": 31,
    # "flatfish": 32,
    # "forest": 33,
    # "fox": 34,
    # "girl": 35,
    # "hamster": 36,
    # "house": 37,
    # "kangaroo": 38,
    # "keyboard": 39,
    # "lamp": 40,
    # "lawn_mower": 41,
    # "leopard": 42,
    # "lion": 43,
    # "lizard": 44,
    # "lobster": 45,
    # "man": 46,
    # "maple_tree": 47,
    # "motorcycle": 48,
    # "mountain": 49,
    # "mouse": 50,
    # "mushroom": 51,
    # "oak_tree": 52,
    # "orange": 53,
    # "orchid": 54,
    # "otter": 55,
    "palm_tree": 56,
    # "pear": 57,
    # "pickup_truck": 58,
    # "pine_tree": 59,
    # "plain": 60,
    # "plate": 61,
    # "poppy": 62,
    # "porcupine": 63,
    # "possum": 64,
    # "rabbit": 65,
    # "raccoon": 66,
    # "ray": 67,
    # "road": 68,
    "rocket": 69,
    # "rose": 70,
    # "sea": 71,
    # "seal": 72,
    # "shark": 73,
    # "shrew": 74,
    # "skunk": 75,
    # "skyscraper": 76,
    "snail": 77,
    "snake": 78,
    "spider": 79,
    # "squirrel": 80,
    # "streetcar": 81,
    # "sunflower": 82,
    # "sweet_pepper": 83,
    # "table": 84,
    # "tank": 85,
     "telephone": 86,
     "television": 87,
    # "tiger": 88,
    # "tractor": 89,
    # "train": 90,
    # "trout": 91,
    # "tulip": 92,
    # "turtle": 93,
    # "wardrobe": 94,
    # "whale": 95,
    # "willow_tree": 96,
    # "wolf": 97,
    # "woman": 98,
    # "worm": 99
}
